name: New Service
about: Create a new service
title: New Service
labels:
  - NewService
body:
  - type: input
    id: service_name
    attributes:
      label: Service Name
      placeholder: Enter the service name
    validations:
      required: true
  - type: input
    id: app_name
    attributes:
      label: App Name
      placeholder: Enter the app name
    validations:
      required: true
  - type: input
    id: repository_name
    attributes:
      label: Repository Name
      placeholder: Enter the repository name
    validations:
      required: true
  - type: input
    id: owner
    attributes:
      label: Owner
      placeholder: Enter the owner
    validations:
      required: true

outputs:
  - label: apiVersion
    value: acme.com/v1
  - label: kind
    value: Service
  - label: metadata:
    value: name: {{service_name}}
  - label: labels:
    value: app: {{app_name}}
  - label: repo:
    value: name: {{repository_name}}
  - label: owner:
    value: {{owner}}