name: Create Service File

on:
  issues:
    types: [opened]

jobs:
  create_service_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract issue details
        id: extract
        run: |
          SERVICE_NAME=$(echo "${{ github.event.issue.body }}" | awk '/### Service Name/{getline; print}' | tr -d '\r')
          APP_NAME=$(echo "${{ github.event.issue.body }}" | awk '/### App Name/{getline; print}' | tr -d '\r')
          REPO_NAME=$(echo "${{ github.event.issue.body }}" | awk '/### Repository Name/{getline; print}' | tr -d '\r')
          REPO_OWNER=$(echo "${{ github.event.issue.body }}" | awk '/### Repository Owner/{getline; print}' | tr -d '\r')
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV

      - name: Debug extracted values
        run: |
          echo "SERVICE_NAME=${{ env.SERVICE_NAME }}"
          echo "APP_NAME=${{ env.APP_NAME }}"
          echo "REPO_NAME=${{ env.REPO_NAME }}"
          echo "REPO_OWNER=${{ env.REPO_OWNER }}"

      - name: Create YAML file
        run: |
          mkdir -p services
          echo "apiVersion: acme.com/v1
          kind: Service
          metadata:
            name: ${{ env.SERVICE_NAME }}
          labels:
            app: ${{ env.APP_NAME }}
          repo:
            name: ${{ env.REPO_NAME }}
            owner: ${{ env.REPO_OWNER }}" > services/${{ env.SERVICE_NAME }}.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add services/${{ env.SERVICE_NAME }}.yaml
          git commit -m "Add new service ${{ env.SERVICE_NAME }}"
          git push

      - name: Close the issue
        run: gh issue close $GITHUB_ISSUE_NUMBER --comment "Auto closing issue"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}