name: Create Service File

on:
  issues:
    types: [opened]

jobs:
  create_service_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: print issue body
        run: echo "${{ github.event.issue.body }}"

      - name: Extract issue details
        id: extract
        run: |
          SERVICE_NAME=$(echo "${{ github.event.issue.body }}" | grep -A 1 'Service Name' | tail -n 1 | xargs)
          APP_NAME=$(echo "${{ github.event.issue.body }}" | grep -A 1 'App Name' | tail -n 1 | xargs)
          REPO_NAME=$(echo "${{ github.event.issue.body }}" | grep -A 1 'Repository Name' | tail -n 1 | xargs)
          REPO_OWNER=$(echo "${{ github.event.issue.body }}" | grep -A 1 'Repository Owner' | tail -n 1 | xargs)
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV

      - name: Create YAML file
        run: |
          mkdir -p services
          FILE_CONTENT=$(cat <<EOF
          apiVersion: acme.com/v1
          kind: Service
          metadata:
            name: ${{ env.SERVICE_NAME }}
          labels:
            app: ${{ env.APP_NAME }}
          repo:
            name: ${{ env.REPO_NAME }}
            owner: ${{ env.REPO_OWNER }}
          EOF
          )
          echo "$FILE_CONTENT" > services/${{ env.SERVICE_NAME }}.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add services/${{ env.SERVICE_NAME }}.yaml
          git commit -m "Add new service ${{ env.SERVICE_NAME }}"
          git push